# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /feedstock/recipe, last modified Thu Jan 26 16:54:55 2023
# ------------------------------------------------

package:
  name: virtualenv
  version: 20.17.1
source:
  sha256: f8b927684efc6f1cc206c9db297a570ab9ad0e51c16fa9e45487d36d1905c058
  url: https://pypi.io/packages/source/v/virtualenv/virtualenv-20.17.1.tar.gz
build:
  entry_points:
    - virtualenv = virtualenv.__main__:run_with_catch
  number: '0'
  script: /croot/virtualenv_1674752100526/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . -vv --no-deps
  string: py310h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2023.01.10 h06a4308_0
    - certifi 2022.12.7 py310h06a4308_0
    - flit-core 3.6.0 pyhd3eb1b0_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.2 h6a678d5_6
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 1.1.1s h7f8727e_0
    - packaging 22.0 py310h06a4308_0
    - pip 22.3.1 py310h06a4308_0
    - python 3.10.9 h7a1cb2a_0
    - readline 8.2 h5eee18b_0
    - setuptools 65.6.3 py310h06a4308_0
    - setuptools-scm 7.0.4 py310h06a4308_0
    - setuptools_scm 7.0.4 hd3eb1b0_0
    - sqlite 3.40.1 h5082296_0
    - tk 8.6.12 h1ccaba5_0
    - tomli 2.0.1 py310h06a4308_0
    - typing-extensions 4.4.0 py310h06a4308_0
    - typing_extensions 4.4.0 py310h06a4308_0
    - tzdata 2022g h04d1e81_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.10 h5eee18b_1
    - zlib 1.2.13 h5eee18b_0
  run:
    - distlib >=0.3.6,<1
    - filelock >=3.4.1,<4
    - platformdirs >=2.4,<3
    - python >=3.10,<3.11.0a0
test:
  commands:
    - pip check
    - virtualenv --help
  imports:
    - virtualenv
    - virtualenv.activation
    - virtualenv.app_data
    - virtualenv.config
    - virtualenv.create
    - virtualenv.discovery
    - virtualenv.run
    - virtualenv.seed
    - virtualenv.util
  requires:
    - pip
about:
  description: 'A tool for creating isolated virtual python environments.

    '
  dev_url: https://github.com/pypa/virtualenv
  doc_url: https://virtualenv.pypa.io/
  home: https://virtualenv.pypa.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Virtual Python Environment builder
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 49642ebe-4d84-4c58-8ac0-fbd847c533f9
  recipe-maintainers:
    - kalefranz
    - mingwandroid
  remote_url: git@github.com:AnacondaRecipes/virtualenv-feedstock.git
  sha: e5b5ea4a3e7c1dc4898b95e97835ad60ed4ba3ef
