# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# /feedstock/recipe, last modified Thu Sep 22 06:16:42 2022
# ------------------------------------------------

package:
  name: contourpy
  version: 1.0.5
source:
  sha256: 896631cd40222aef3697e4e51177d14c3709fda49d30983269d584f034acc8a4
  url: https://pypi.io/packages/source/c/contourpy/contourpy-1.0.5.tar.gz
build:
  number: '0'
  script: /opt/conda/conda-bld/contourpy_1663827406301/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . -vv
  string: py310hdb19cb5_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.38 h2a08ee3_1
    - binutils_linux-64 2.38.0 hc2dff05_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_0
    - gxx_impl_linux-64 11.2.0 h1234567_1
    - gxx_linux-64 11.2.0 hc2dff05_0
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.38 h1181459_1
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-devel_linux-64 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2022.07.19 h06a4308_0
    - certifi 2022.9.14 py310h06a4308_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.3 he6710b0_2
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.0.3 h7f8727e_2
    - ncurses 6.3 h5eee18b_3
    - openssl 1.1.1q h7f8727e_0
    - packaging 21.3 pyhd3eb1b0_0
    - pep517 0.12.0 py310h06a4308_0
    - pip 22.1.2 py310h06a4308_0
    - pybind11 2.9.2 py310h3c18c91_0
    - pyparsing 3.0.9 py310h06a4308_0
    - python 3.10.4 h12debd9_0
    - python-build 0.7.0 pyhd3eb1b0_0
    - readline 8.1.2 h7f8727e_1
    - setuptools 63.4.1 py310h06a4308_0
    - sqlite 3.39.2 h5082296_0
    - tk 8.6.12 h1ccaba5_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tomli 2.0.1 py310h06a4308_0
    - tzdata 2022c h04d1e81_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h7f8727e_1
    - zlib 1.2.12 h5eee18b_3
  run:
    - libgcc-ng >=11.2.0
    - libstdcxx-ng >=11.2.0
    - numpy >=1.16
    - python >=3.10,<3.11.0a0
test:
  commands:
    - pip check
    - python -c "import contourpy as c; c.contour_generator(z=[[0, 1], [2, 3]]).lines(0.9)"
  imports:
    - contourpy
    - contourpy.util
  requires:
    - pip
about:
  description: 'ContourPy is a Python library for calculating contours of 2D quadrilateral

    grids.  It is written in C++11 and wrapped using pybind11.

    '
  dev_url: https://github.com/contourpy/contourpy
  doc_sourc_url: https://github.com/contourpy/contourpy/tree/main/docs
  doc_url: https://contourpy.readthedocs.io
  home: https://github.com/contourpy/contourpy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  license_url: https://github.com/contourpy/contourpy/blob/main/LICENSE
  summary: Python library for calculating contours of 2D quadrilateral grids.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 1377ca31-1618-4447-9c15-321a9c3845d1
  recipe-maintainers:
    - ianthomas23
  remote_url: git@github.com:AnacondaRecipes/contourpy-feedstock.git
  sha: c3682854f6d9e0cf66cb39514bc12789fa40a9d9
