# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /feedstock/recipe, last modified Fri Mar  3 09:26:15 2023
# ------------------------------------------------

package:
  name: pandas
  version: 1.5.3
source:
  sha256: 74a3fd7e5a7ec052f183273dc7b0acd3a863edf7520f5d3a1765c04ffdb3b0b1
  url: https://github.com/pandas-dev/pandas/releases/download/v1.5.3/pandas-1.5.3.tar.gz
build:
  entry_points:
    - matplotlib = pandas:plotting._matplotlib
  number: '0'
  script:
    - /croot/pandas_1677835581022/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
      -m pip install -vv --no-deps --ignore-installed . --global-option="build_ext"
      --global-option="-j1" --no-use-pep517
  string: py310h1128e8f_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.38 h2a08ee3_1
    - binutils_linux-64 2.38.0 hc2dff05_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_0
    - gxx_impl_linux-64 11.2.0 h1234567_1
    - gxx_linux-64 11.2.0 hc2dff05_0
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.38 h1181459_1
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-devel_linux-64 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - blas 1.0 mkl
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2023.01.10 h06a4308_0
    - certifi 2022.12.7 py310h06a4308_0
    - cython 0.29.33 py310h6a678d5_0
    - intel-openmp 2021.4.0 h06a4308_3561
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.2 h6a678d5_6
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - mkl 2021.4.0 h06a4308_640
    - mkl-service 2.4.0 py310h7f8727e_0
    - mkl_fft 1.3.1 py310hd6ae3a3_0
    - mkl_random 1.2.2 py310h00e6091_0
    - ncurses 6.4 h6a678d5_0
    - numpy 1.21.5 py310h1794996_3
    - numpy-base 1.21.5 py310hcba007f_3
    - openssl 1.1.1t h7f8727e_0
    - pip 22.3.1 py310h06a4308_0
    - python 3.10.9 h7a1cb2a_1
    - readline 8.2 h5eee18b_0
    - setuptools 65.6.3 py310h06a4308_0
    - six 1.16.0 pyhd3eb1b0_1
    - sqlite 3.40.1 h5082296_0
    - tk 8.6.12 h1ccaba5_0
    - tzdata 2022g h04d1e81_0
    - wheel 0.38.4 py310h06a4308_0
    - xz 5.2.10 h5eee18b_1
    - zlib 1.2.13 h5eee18b_0
  run:
    - bottleneck >=1.3.2
    - libgcc-ng >=11.2.0
    - libstdcxx-ng >=11.2.0
    - numexpr >=2.7.3
    - numpy >=1.21,<2.0a0
    - python >=3.10,<3.11.0a0
    - python-dateutil >=2.8.1
    - pytz >=2020.1
  run_constrained:
    - beautifulsoup4 >=4.9.3
    - blosc >=1.21.0
    - brotli >=0.7.0
    - fastparquet >=0.4.0
    - fsspec >=2021.7.0
    - gcsfs >=2021.7.0
    - html5lib >=1.1
    - jinja2 >=3.0.0
    - lxml >=4.6.3
    - matplotlib-base >=3.3.2
    - numba >=0.53.1
    - openpyxl >=3.0.7
    - pandas-gbq >=0.15.0
    - psycopg2 >=2.8.6
    - pyarrow >=1.0.1
    - pymysql >=1.0.2
    - pyreadstat >=1.1.2
    - pytables >=3.6.1
    - python-snappy >=0.6.0
    - pyxlsb >=1.0.8
    - s3fs >=2021.08.0
    - scipy >=1.7.1
    - sqlalchemy >=1.4.16
    - tabulate >=0.8.9
    - tzdata >=2022a
    - xarray >=0.19.0
    - xlrd >=2.0.1
    - xlsxwriter >=1.4.3
    - xlwt >=1.3.0
    - zstandard >=0.15.2
test:
  commands:
    - pip check
  requires:
    - hypothesis >=6.13.0
    - pip
    - pytest >=6.0
    - pytest-xdist >=1.31
about:
  description: 'pandas is a Python package that provides fast, flexible, and expressive
    data structures

    designed to make working with "relational" or "labeled" data both easy and intuitive.

    It aims to be the fundamental high-level building block for doing practical, real
    world

    data analysis in Python. Additionally, it has the broader goal of becoming the
    most

    powerful and flexible open source data analysis / manipulation tool available
    in any

    language. It is already well on its way towards this goal.

    '
  dev_url: https://github.com/pandas-dev/pandas
  doc_url: https://pandas.pydata.org/pandas-docs/version/1.5.3/index.html
  home: https://pandas.pydata.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: High-performance, easy-to-use data structures and data analysis tools.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 901405e9-b645-4905-bf85-ec57def546fa
  recipe-maintainers:
    - TomAugspurger
    - WillAyd
    - jorisvandenbossche
    - jreback
    - msarahan
    - ocefpaf
    - simonjayhawkins
  remote_url: git@github.com:AnacondaRecipes/pandas-feedstock.git
  sha: 8fb59ac6dfb05c10aae90bb2ed1ff895bc9e6e43
  skip-lints:
    - has_run_test_and_commands
