# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /feedstock/recipe, last modified Thu Nov 17 19:38:04 2022
# ------------------------------------------------

package:
  name: numexpr
  version: 2.8.4
source:
  sha256: d5432537418d18691b9115d615d6daa17ee8275baef3edf1afbbf8bc69806147
  url: https://pypi.io/packages/source/n/numexpr/numexpr-2.8.4.tar.gz
build:
  number: '0'
  script: /croot/numexpr_1668713893690/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install . --no-deps -vv
  string: py310h757a811_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.38 h2a08ee3_1
    - binutils_linux-64 2.38.0 hc2dff05_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_0
    - gxx_impl_linux-64 11.2.0 h1234567_1
    - gxx_linux-64 11.2.0 hc2dff05_0
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.38 h1181459_1
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-devel_linux-64 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - blas 1.0 openblas
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2022.10.11 h06a4308_0
    - certifi 2022.9.24 py310h06a4308_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.3 he6710b0_2
    - libgcc-ng 11.2.0 h1234567_1
    - libgfortran-ng 11.2.0 h00389a5_1
    - libgfortran5 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libopenblas 0.3.20 h043d6bf_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.3 h5eee18b_3
    - nomkl 3.0 0
    - numpy 1.21.5 py310hac523dd_3
    - numpy-base 1.21.5 py310h375b286_3
    - openblas-devel 0.3.20 h06a4308_1
    - openssl 1.1.1s h7f8727e_0
    - pip 22.2.2 py310h06a4308_0
    - python 3.10.8 haa1d7c7_0
    - readline 8.2 h5eee18b_0
    - setuptools 65.5.0 py310h06a4308_0
    - sqlite 3.39.3 h5082296_0
    - tk 8.6.12 h1ccaba5_0
    - tzdata 2022f h04d1e81_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.6 h5eee18b_0
    - zlib 1.2.13 h5eee18b_0
  run:
    - blas * openblas
    - libgcc-ng >=11.2.0
    - libopenblas >=0.3.20,<1.0a0
    - libstdcxx-ng >=11.2.0
    - numpy >=1.21.5,<2.0a0
    - packaging
    - python >=3.10,<3.11.0a0
test:
  commands:
    - pip check
  imports:
    - numexpr
    - numexpr.interpreter
  requires:
    - nomkl
    - pip
about:
  description: 'Numexpr is a fast numerical expression evaluator for NumPy. With it,

    expressions that operate on arrays (like "3*a+4*b") are accelerated and use

    less memory than doing the same calculation in Python.

    '
  dev_url: https://github.com/pydata/numexpr
  doc_url: https://github.com/pydata/numexpr/wiki/Numexpr-Users-Guide
  home: https://github.com/pydata/numexpr
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Fast numerical expression evaluator for NumPy.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: e5eac76a-f775-4055-9def-213194c80985
  recipe-maintainers:
    - djkirkham
    - msarahan
    - ocefpaf
    - scopatz
  remote_url: git@github.com:AnacondaRecipes/numexpr-feedstock.git
  sha: a87b517512d42b5f6eecb1d1ea4ae834cf63c195
