name: documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Set up poetry cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pypoetry/
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock', 'pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install      

    - name: Sphinx build
      run: |
        poetry run sphinx-build docs _site

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
