name: Test package

on: [ push, pull_request ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'
    - name: Set up poetry cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pypoetry/
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install      
    - name: Install dependencies for documentation
      run: |
        poetry add sphinx sphinx_rtd_theme sphinx_copybutton myst_parser
    - name: Sphinx build
      run: |
        poetry run sphinx-build docs _site
    - name: Run tests
      run: |
        poetry run pytest -v
    - name: Run coverage
      run: |
        poetry run coverage run -m pytest
        poetry run coverage report
    - name: Format with black
      run: |
        poetry run black --check .
